// ─── Observed Facts ───────────────────────────────────────────────────────────
//
// Observed facts are created by sensors, databases, and source reports.
// The LLM does not create observed facts. It receives them and interprets them.

export type FactDomain =
  | "UAS"
  | "cyber"
  | "maritime"
  | "ground"
  | "air"
  | "space"
  | "information"
  | "logistics"
  | "signals";

export type ConfidenceLevel = "low" | "medium" | "high";
export type SeverityLevel = "low" | "medium" | "high" | "critical";

export type ObservedFact = {
  /** Stable, source-assigned ID. e.g. "fact_uas_001". Never generated by the LLM. */
  id: string;
  domain: FactDomain;
  /** The primary entity involved (e.g. "Port A", "Vessel Kalmar") */
  entity: string;
  /** What was observed (e.g. "unidentified UAS sighting") */
  event: string;
  /** ISO 8601 or HH:mm string */
  time: string;
  location?: string;
  /** Optional geolocation used for map rendering */
  coordinates?: {
    lat: number;
    lng: number;
  };
  /** Who or what produced this fact */
  source: string;
  confidence: ConfidenceLevel;
  severity: SeverityLevel;
  /** Pointer to raw evidence (sensor log, report ID, etc.) — not transmitted to LLM */
  rawEvidenceRef?: string;
  /** Whether this fact was loaded from intelligence or bundled scenario demo data. */
  sourceType?: "loaded-fact" | "scenario-demo";
  /** How map coordinates were resolved for visualization. */
  coordinateType?: "reported" | "derived" | "stub";
};

// ─── Source Reports ───────────────────────────────────────────────────────────
//
// Raw, unstructured or semi-structured inputs from sensors and sources.
// The fact normalizer converts these into ObservedFact records.

export type RawSourceReport = {
  reportId: string;
  source: string;
  domain: FactDomain;
  timestamp: string;
  text: string;
  metadata?: Record<string, unknown>;
};

// ─── Scenario Packet ─────────────────────────────────────────────────────────
//
// The bounded input given to the LLM. Contains only what the LLM should see.
// The LLM cannot know about facts not included here.

export type ScenarioPacket = {
  commanderIntent: string;
  observedFacts: ObservedFact[];
  knownAssets: string[];
  /** Authority state registry keyed by authority name (e.g. "airspace-authorization") */
  knownAuthorities?: Record<string, AuthorityState>;
  /**
   * Hard rules the LLM must follow when reasoning.
   * Enforced both by prompt and by the grounding validator.
   */
  constraints: string[];
  contextWindow?: string;
};

// ─── LLM Interpretation ───────────────────────────────────────────────────────
//
// What the LLM returns. Every field that makes a claim must cite fact IDs.
// The grounding validator checks every ID against the known fact set.

export type Inference = {
  claim: string;
  /** Every cited ID must exist in the scenario packet's observedFacts */
  supportingFacts: string[];
  confidence: ConfidenceLevel;
  /** Required when confidence < "high" — explains what would raise it */
  whyNotHigher?: string;
};

export type Assumption = {
  claim: string;
  status: "unconfirmed" | "working-assumption";
};

export type AuthorityState =
  | "authorized"
  | "requires-approval"
  | "prohibited"
  | "unknown";

export type CandidateActionType =
  | "observe"
  | "monitor"
  | "investigate"
  | "coordinate"
  | "preserve"
  | "inform"
  | "harden"
  | "other";

export type TimeSensitivity = "immediate" | "time-bound" | "routine";

export type DecisionTier = "watch-floor" | "section-lead" | "commander";

export type DecisionOptionStatus =
  | "executable"
  | "requires-command-decision"
  | "not-available";

export type DecisionOptionGrounding = "explicit" | "inherited" | "missing";

export type DecisionOption = {
  id: string;
  label: string;
  actionType: CandidateActionType;
  benefits: string[];
  risks: string[];
  requiredAssets: string[];
  requiredAuthority: string[];
  secondOrderEffects: string[];
  confidence: ConfidenceLevel;
  citedFacts: string[];
  /** True when citedFacts was inherited from parent triggerFacts */
  citedFactsInherited?: boolean;
  grounding?: DecisionOptionGrounding;
  status?: DecisionOptionStatus;
};

export type DecisionPoint = {
  id: string;
  question: string;
  triggerFacts: string[];
  options: DecisionOption[];
  deadline?: string;
  commanderLevel: DecisionTier;
  reversible: boolean;
  informationNeeded: string[];
  triggerCondition?: string;
  escalationThreshold?: string;
  deescalationThreshold?: string;
  abortCondition?: string;
};

/**
 * A candidate action is something the LLM proposes for the COA solver to consider.
 * It is NOT an executable order. The solver decides whether to include it.
 *
 * Every candidate action must cite at least one observed fact.
 * Recommendations citing only inferences are flagged by the grounding validator.
 */
export type CandidateAction = {
  id: string;
  description: string;
  actionType?: CandidateActionType;
  purpose?: string;
  /** Fact IDs that directly support this recommendation */
  citedFacts: string[];
  /** Inference IDs (within this interpretation) that also support it */
  citedInferences: string[];
  requiredAssets?: string[];
  requiredAuthority?: string[];
  expectedEffects?: string[];
  timeSensitivity?: TimeSensitivity;
  recommendedOwner?: string;
  risks?: string[];
  conflicts?: string[];
  assumptions?: string[];
  confidence?: ConfidenceLevel;
  /**
   * Allowed hedge language only. Must not use: "proves", "confirms", "shows
   * adversary did X". Should use: "may indicate", "is consistent with",
   * "could suggest", "requires confirmation".
   */
  rationale: string;
};

export type LLMInterpretation = {
  /** Fact IDs the LLM actually used. Must be a subset of the scenario packet. */
  observedFactsUsed: string[];
  inferences: Inference[];
  decisionPoints: DecisionPoint[];
  assumptions: Assumption[];
  uncertainties: string[];
  candidateActions: CandidateAction[];
};

// ─── Grounding Validation ─────────────────────────────────────────────────────
//
// The deterministic layer that runs after the LLM returns.
// It does not use the LLM to check the LLM.

export type GroundingIssue =
  | { kind: "hallucinated-fact-id"; id: string }
  | { kind: "unsupported-inference"; claim: string; reason: string }
  | { kind: "unsupported-action"; actionId: string; reason: string }
  | { kind: "unsupported-decision-option"; decisionPointId: string; optionId: string; reason: string }
  | { kind: "degraded-grounding"; decisionPointId: string; optionId: string; reason: string }
  | { kind: "unknown-asset"; actionId: string; asset: string }
  | { kind: "missing-authority-state"; actionId: string; authority: string }
  | {
      kind: "invented-entity";
      entity: string;
      foundIn: string;
      actionId?: string;
      decisionPointId?: string;
      optionId?: string;
    }
  | {
      kind: "constraint-violation";
      constraint: string;
      foundIn: string;
      actionId?: string;
      decisionPointId?: string;
      optionId?: string;
    }
  | {
      kind: "hedge-violation";
      claim: string;
      forbiddenWord: string;
      actionId?: string;
      decisionPointId?: string;
      optionId?: string;
    }
  | {
      kind: "confidence-exceeds-evidence";
      actionId: string;
      reason: string;
    }
  | {
      kind: "evidence-conflict";
      conflictId: string;
      actionId: string;
      reason: string;
    };

export type GroundingValidationResult = {
  valid: boolean;
  hasIssues: boolean;
  blockingIssues: number;
  reviewIssues: number;
  usableForPlanning: boolean;
  issues: GroundingIssue[];
  /** Deterministic flags from observed facts (degraded source, contradiction, etc.). */
  evidenceConflicts: import("./evidence").EvidenceConflict[];
  /** Fact IDs that were in the packet but the LLM never cited */
  unusedFacts: string[];
  /** Candidate actions that passed all grounding checks */
  validatedActionIds: string[];
  /** Decision points with options that passed deterministic checks */
  validatedDecisionPointIds: string[];
};

// ─── Intel State ──────────────────────────────────────────────────────────────
//
// The full state of the intelligence layer, committed atomically
// after validation completes.

export type IntelState = {
  status: "idle" | "collecting" | "interpreting" | "validating" | "ready" | "error";
  error?: string;

  /** Normalized facts from this collection cycle */
  facts: ObservedFact[];

  /** The packet given to the LLM (kept for audit/display) */
  scenarioPacket?: ScenarioPacket;

  /** Raw LLM output (kept for audit) */
  rawInterpretation?: LLMInterpretation;
  /** Raw model text response before JSON extraction/normalization */
  rawModelText?: string;

  /** Grounding validation result */
  groundingResult?: GroundingValidationResult;

  /**
   * The validated candidate actions — the ONLY thing that flows downstream
   * to the COA pipeline's collectSignals().
   * Actions that failed grounding are excluded.
   */
  validatedActions: CandidateAction[];
  validatedDecisionPoints: DecisionPoint[];
};
